<?php

function bobpol_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form") {
    if (isset($form['combine'])) {
      $form['combine']['#attributes'] = array('data-bef-auto-submit-exclude' => '');
    }
  };
}

function bobpol_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#type'])) {
    $suggestions[] = 'form_element__' . $variables['element']['#type'];
  }
}